apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fridiks-no
resources:
  - ../../../base
commonLabels:
  app.kubernetes.io/name: fint-kontroll-resource-gateway
  app.kubernetes.io/instance: fint-kontroll-resource-gateway_fridiks-no
  app.kubernetes.io/version: latest
  app.kubernetes.io/component: backend
  app.kubernetes.io/part-of: fint-kontroll
  fintlabs.no/team: bas
  fintlabs.no/org-id: fridiks.no

patches:
  - patch: |-
      - op: replace
        path: "/spec/orgId"
        value: "fridiks.no"
    target:
      kind: FintClient
      name: kontroll-resource-gw
  - patch: |-
      - op: replace
        path: "/spec/orgId"
        value: "fridiks.no"
      - op: add
        path: "/spec/resources"
        value:
          limits:
            cpu: "1000m"
            memory: "2000Mi"
          requests:
            cpu: "500m"
            memory: "1000Mi"
      - op: replace
        path: "/spec/env/0/value"
        value: "https://api.felleskomponent.no"
      - op: replace
        path: "/spec/env/1/value"
        value: "fint"
      - op: replace
        path: "/spec/env/2/value"
        value: "enabled"
      - op: replace
        path: "/spec/env/3/value"
        value: "fridiks-no-fint-kontroll-resource-gateway"
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "fridiks-no.kontroll.*"
      - op: replace
        path: "/spec/kafka/acls/1/topic"
        value: "fridiks-no.kontroll.*"
      - op: remove
        path: "/spec/config/application.yaml/entity-pipelines/4"
      - op: remove
        path: "/spec/config/application.yaml/entity-pipelines/5"
      - op: remove
        path: "/spec/config/application.yaml/entity-pipelines/6"
      - op: remove
        path: "/spec/config/application.yaml/entity-pipelines/7"
      - op: remove
        path: "/spec/config/application.yaml/entity-pipelines/8"
      - op: remove
        path: "/spec/config/application.yaml/entity-pipelines/9"
      - op: remove
        path: "/spec/config/application.yaml/entity-pipelines/10"
    target:
      kind: Application
      name: fint-kontroll-resource-gateway
