novari:
  kafka:
    default-replicas: 1
    topic:
      org-id: fintlabs-no
      domain-context: kontroll
    application-id: ${fint.application-id}

spring:
  kafka:
    consumer:
      group-id: ${fint.application-id}
    producer:
      properties:
        max:
          request:
            size: 2097152

