apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: afk-no
resources:
  - ../../../base
commonLabels:
  app.kubernetes.io/name: fint-kontroll-resource-gateway
  app.kubernetes.io/instance: fint-kontroll-resource-gateway_afk-no
  app.kubernetes.io/version: latest
  app.kubernetes.io/component: backend
  app.kubernetes.io/part-of: fint-kontroll
  fintlabs.no/team: bas
  fintlabs.no/org-id: afk.no

patches:
  - patch: |-
      - op: replace
        path: "/spec/orgId"
        value: "afk.no"
    target:
      kind: FintClient
      name: kontroll-resource-gw
  - patch: |-
      - op: add
        path: "/spec/resources"
        value:
          limits:
            cpu: "1500m"
            memory: "1000Mi"
          requests:
            cpu: "500m"
            memory: "1000Mi"
      - op: replace
        path: "/spec/orgId"
        value: "afk.no"
      - op: replace
        path: "/spec/env/0/value"
        value: "https://api.felleskomponent.no"
      - op: replace
        path: "/spec/env/1/value"
        value: "fint"
      - op: replace
        path: "/spec/env/2/value"
        value: "enabled"
      - op: replace
        path: "/spec/env/3/value"
        value: "afk-no-fint-kontroll-resource-gateway"
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "afk-no.kontroll.*"
      - op: replace
        path: "/spec/kafka/acls/1/topic"
        value: "afk-no.kontroll.*"
    target:
      kind: Application
      name: fint-kontroll-resource-gateway
