apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-kontroll-resource-gateway
  namespace: fintlabs-no
spec:
  orgId: fintlabs.no
  image: ghcr.io/fintlabs/fint-kontroll-resource-gateway:latest
  imagePullPolicy: Always
  env:
    - name: fint.client.base-url
      value: 'http://fint-kontroll-mock-service:3000'
    - name: fint.kontroll.datainput
      value: 'mock'
    - name: fint.resource-gateway.authorization
      value: 'disabled'
    - name:
    - name: fint.resource-gateway.resources.entity.entity-pipelines
      value:
        - resource-reference: administrasjon.personal.personalressurs
          self-link-key-filter: ansattnummer
        - resource-reference: administrasjon.personal.person
          self-link-key-filter: fodselsnummer
        - resource-reference: administrasjon.personal.arbeidsforhold
          self-link-key-filter: systemid
        - resource-reference: administrasjon.organisasjon.organisasjonselement
          self-link-key-filter: organisasjonsid
        - resource-reference: utdanning.elev.person
          self-link-key-filter: fodselsnummer
        - resource-reference: utdanning.elev.elev
          self-link-key-filter: systemid
        - resource-reference: utdanning.elev.elevforhold
          self-link-key-filter: systemid
        - resource-reference: utdanning.utdanningsprogram.skole
          self-link-key-filter: systemid
  kafka:
    enabled: true
    acls:
      - topic: 'fintlabs-no.kontroll.*'
        permission: read
      - topic: 'fintlabs-no.kontroll.*'
        permission: admin



#  envFrom:
#    - configMapRef:
#        name: fint-environment
#    - configMapRef:
#        name: fint-kontroll-resourcegateway-config


