apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: fint-kontroll-resource-gateway
  app.kubernetes.io/instance: fint-kontroll-resource-gateway_fintlabs_no
  app.kubernetes.io/version: latest
  app.kubernetes.io/component: gateway
  app.kubernetes.io/part-of: fint-kontroll
  fintlabs.no/team: bas
  fintlabs.no/org-id: fintlabs.no
namespace: fintlabs-no

resources:
  - flais.yaml
  - fint-config.yaml

