apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fintlabs-no
resources:
  - ../../../base
commonLabels:
  app.kubernetes.io/name: fint-kontroll-resource-gateway
  app.kubernetes.io/instance: fint-kontroll-resource-gateway_fintlabs-no
  app.kubernetes.io/version: latest
  app.kubernetes.io/component: backend
  app.kubernetes.io/part-of: fint-kontroll
  fintlabs.no/team: bas
  fintlabs.no/org-id: fintlabs.no
patches:
  - patch: |-
      - op: replace
        path: "/spec/orgId"
        value: "fintlabs.no"
    target:
      kind: FintClient
      name: kontroll-resource-gw
  - patch: |-
      - op: replace
        path: "/spec/orgId"
        value: "fintlabs.no"
      - op: replace
        path: "/spec/env/0/value"
        value: "http://fint-kontroll-mock-service:3000"
      - op: replace
        path: "/spec/env/1/value"
        value: "mock"
      - op: replace
        path: "/spec/env/2/value"
        value: "disable"
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "fintlabs-no.kontroll.*"
      - op: replace
        path: "/spec/kafka/acls/1/topic"
        value: "fintlabs.kontroll.*"
    target:
      kind: Application
      name: fint-kontroll-resource-gateway

          
          

        
