apiVersion: apps/v1
kind: Deployment
metadata:
  name: fint-kontroll-resource-gateway
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: fint-kontroll-resource-gateway
    spec:
      terminationGracePeriodSeconds: 60
      volumes:
        - name: credentials
          secret:
            secretName: fint-kontroll-resource-gateway-kafka-certificates
      containers:
        - image: ghcr.io/fintlabs/fint-kontroll-resource-gateway:latest
          name: fint-kontroll-resource-gateway
          volumeMounts:
            - name: credentials
              mountPath: /credentials
          resources:
            limits:
              memory: "2048Mi"
              cpu: "1"
            requests:
              memory: "512Mi"
              cpu: "100m"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: fint-kontroll-resource-gateway
            - secretRef:
                name: fint-kontroll-resource-gateway-kafka


